### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by kubo-von** [Traverse-Research/ogawa-rs#22]
Hello,
Thanks for making this create and sharing it. It's awesome to have pure rust option to read abc data. 
Would it be possible to add a simple example ? E.g opening an .abc file and reading primvars and attributes of one of the meshes/curves ? 

Than you!

**Comment by Jasper-Bekkers** [comment]
We ship 3 examples in the `apps` folder of the repo, maybe you can PR it so it works with `cargo example`?

**Comment by kubo-von** [comment]
Oh sorry, that's my bad, I was just looking for /examples folder or something in the docs, didn't check the apps folder *facepalm* . 
Thanks! Will try to make a PR with examples..

**Comment by Jasper-Bekkers** [comment]
Thanks!

**Comment by Jasper-Bekkers** [comment]
Is that enough to make it function with `cargo run --example`? If so, then I think that's perfectly reasonable. Otherwise we probably should make sure to get that to work, probably by moving dependencies to dev-dependencies.

**Comment by MarijnS95** [comment]
@kubo-von it looks like all `apps/` are single-file binary examples that can easily be moved to a new `examples/` folder (adopting the name of the original crate).

As said by Jasper, crate dependencies should be moved into `[dev-dependencies]` on the root of the crate. Once done, don't forget to remove the `[workspace]` table from the root :)

**Comment by kubo-von** [comment]
The PR is here #28
